//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="AspectWsBinding", Namespace="https://my.oilspace.net/webservice/aspectws/wsdl11")]
public partial class AspectWs : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback addOptionPriceOperationCompleted;
    
    private System.Threading.SendOrPostCallback addOptionPriceBulkOperationCompleted;
    
    private System.Threading.SendOrPostCallback getAllOptionInstrumentsOperationCompleted;
    
    private System.Threading.SendOrPostCallback isBankHolidayOperationCompleted;
    
    private System.Threading.SendOrPostCallback mstest_getOptionInstrumentOperationCompleted;
    
    private System.Threading.SendOrPostCallback myQueryOperationCompleted;
    
    private System.Threading.SendOrPostCallback updateDCOperationCompleted;
    
    /// <remarks/>
    public AspectWs() {
        this.Url = "https://test.myaspect.net/webservice/aspectws";
    }
    
    /// <remarks/>
    public event addOptionPriceCompletedEventHandler addOptionPriceCompleted;
    
    /// <remarks/>
    public event addOptionPriceBulkCompletedEventHandler addOptionPriceBulkCompleted;
    
    /// <remarks/>
    public event getAllOptionInstrumentsCompletedEventHandler getAllOptionInstrumentsCompleted;
    
    /// <remarks/>
    public event isBankHolidayCompletedEventHandler isBankHolidayCompleted;
    
    /// <remarks/>
    public event mstest_getOptionInstrumentCompletedEventHandler mstest_getOptionInstrumentCompleted;
    
    /// <remarks/>
    public event myQueryCompletedEventHandler myQueryCompleted;
    
    /// <remarks/>
    public event updateDCCompletedEventHandler updateDCCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://test.myaspect.net/webservice/aspectws", RequestNamespace="https://my.oilspace.net/webservice/aspectws/schema.xsd", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void addOptionPrice([System.Xml.Serialization.XmlElementAttribute("instrument-price")] addOptionPriceInstrumentprice[] instrumentprice) {
        this.Invoke("addOptionPrice", new object[] {
                    instrumentprice});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaddOptionPrice(addOptionPriceInstrumentprice[] instrumentprice, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("addOptionPrice", new object[] {
                    instrumentprice}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndaddOptionPrice(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void addOptionPriceAsync(addOptionPriceInstrumentprice[] instrumentprice) {
        this.addOptionPriceAsync(instrumentprice, null);
    }
    
    /// <remarks/>
    public void addOptionPriceAsync(addOptionPriceInstrumentprice[] instrumentprice, object userState) {
        if ((this.addOptionPriceOperationCompleted == null)) {
            this.addOptionPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddOptionPriceOperationCompleted);
        }
        this.InvokeAsync("addOptionPrice", new object[] {
                    instrumentprice}, this.addOptionPriceOperationCompleted, userState);
    }
    
    private void OnaddOptionPriceOperationCompleted(object arg) {
        if ((this.addOptionPriceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.addOptionPriceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://test.myaspect.net/webservice/aspectws", RequestNamespace="https://my.oilspace.net/webservice/aspectws/schema.xsd", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void addOptionPriceBulk([System.Xml.Serialization.XmlElementAttribute("instrument-price")] addOptionPriceBulkInstrumentprice[] instrumentprice) {
        this.Invoke("addOptionPriceBulk", new object[] {
                    instrumentprice});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaddOptionPriceBulk(addOptionPriceBulkInstrumentprice[] instrumentprice, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("addOptionPriceBulk", new object[] {
                    instrumentprice}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndaddOptionPriceBulk(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void addOptionPriceBulkAsync(addOptionPriceBulkInstrumentprice[] instrumentprice) {
        this.addOptionPriceBulkAsync(instrumentprice, null);
    }
    
    /// <remarks/>
    public void addOptionPriceBulkAsync(addOptionPriceBulkInstrumentprice[] instrumentprice, object userState) {
        if ((this.addOptionPriceBulkOperationCompleted == null)) {
            this.addOptionPriceBulkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddOptionPriceBulkOperationCompleted);
        }
        this.InvokeAsync("addOptionPriceBulk", new object[] {
                    instrumentprice}, this.addOptionPriceBulkOperationCompleted, userState);
    }
    
    private void OnaddOptionPriceBulkOperationCompleted(object arg) {
        if ((this.addOptionPriceBulkCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.addOptionPriceBulkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://test.myaspect.net/webservice/aspectws", RequestNamespace="https://my.oilspace.net/webservice/aspectws/schema.xsd", ResponseElementName="GetAllOptionInstrumentsResponse", ResponseNamespace="https://my.oilspace.net/webservice/aspectws/schema.xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getAllOptionInstruments")]
    public GetAllOptionInstrumentsResponseGetAllOptionInstruments getAllOptionInstruments() {
        object[] results = this.Invoke("getAllOptionInstruments", new object[0]);
        return ((GetAllOptionInstrumentsResponseGetAllOptionInstruments)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetAllOptionInstruments(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getAllOptionInstruments", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public GetAllOptionInstrumentsResponseGetAllOptionInstruments EndgetAllOptionInstruments(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((GetAllOptionInstrumentsResponseGetAllOptionInstruments)(results[0]));
    }
    
    /// <remarks/>
    public void getAllOptionInstrumentsAsync() {
        this.getAllOptionInstrumentsAsync(null);
    }
    
    /// <remarks/>
    public void getAllOptionInstrumentsAsync(object userState) {
        if ((this.getAllOptionInstrumentsOperationCompleted == null)) {
            this.getAllOptionInstrumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllOptionInstrumentsOperationCompleted);
        }
        this.InvokeAsync("getAllOptionInstruments", new object[0], this.getAllOptionInstrumentsOperationCompleted, userState);
    }
    
    private void OngetAllOptionInstrumentsOperationCompleted(object arg) {
        if ((this.getAllOptionInstrumentsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getAllOptionInstrumentsCompleted(this, new getAllOptionInstrumentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://test.myaspect.net/webservice/aspectws", RequestNamespace="https://my.oilspace.net/webservice/aspectws/schema.xsd", ResponseElementName="IsBankHolidayResponse", ResponseNamespace="https://my.oilspace.net/webservice/aspectws/schema.xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("isBankHoliday")]
    public IsBankHolidayResponseIsBankHoliday isBankHoliday([System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime date) {
        object[] results = this.Invoke("isBankHoliday", new object[] {
                    date});
        return ((IsBankHolidayResponseIsBankHoliday)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginisBankHoliday(System.DateTime date, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("isBankHoliday", new object[] {
                    date}, callback, asyncState);
    }
    
    /// <remarks/>
    public IsBankHolidayResponseIsBankHoliday EndisBankHoliday(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((IsBankHolidayResponseIsBankHoliday)(results[0]));
    }
    
    /// <remarks/>
    public void isBankHolidayAsync(System.DateTime date) {
        this.isBankHolidayAsync(date, null);
    }
    
    /// <remarks/>
    public void isBankHolidayAsync(System.DateTime date, object userState) {
        if ((this.isBankHolidayOperationCompleted == null)) {
            this.isBankHolidayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisBankHolidayOperationCompleted);
        }
        this.InvokeAsync("isBankHoliday", new object[] {
                    date}, this.isBankHolidayOperationCompleted, userState);
    }
    
    private void OnisBankHolidayOperationCompleted(object arg) {
        if ((this.isBankHolidayCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.isBankHolidayCompleted(this, new isBankHolidayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://test.myaspect.net/webservice/aspectws", RequestNamespace="https://my.oilspace.net/webservice/aspectws/schema.xsd", ResponseElementName="Mstest_getOptionInstrumentResponse", ResponseNamespace="https://my.oilspace.net/webservice/aspectws/schema.xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getOptionInstrument")]
    public Mstest_getOptionInstrumentResponseGetOptionInstrument mstest_getOptionInstrument(string contract) {
        object[] results = this.Invoke("mstest_getOptionInstrument", new object[] {
                    contract});
        return ((Mstest_getOptionInstrumentResponseGetOptionInstrument)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginmstest_getOptionInstrument(string contract, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("mstest_getOptionInstrument", new object[] {
                    contract}, callback, asyncState);
    }
    
    /// <remarks/>
    public Mstest_getOptionInstrumentResponseGetOptionInstrument Endmstest_getOptionInstrument(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Mstest_getOptionInstrumentResponseGetOptionInstrument)(results[0]));
    }
    
    /// <remarks/>
    public void mstest_getOptionInstrumentAsync(string contract) {
        this.mstest_getOptionInstrumentAsync(contract, null);
    }
    
    /// <remarks/>
    public void mstest_getOptionInstrumentAsync(string contract, object userState) {
        if ((this.mstest_getOptionInstrumentOperationCompleted == null)) {
            this.mstest_getOptionInstrumentOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmstest_getOptionInstrumentOperationCompleted);
        }
        this.InvokeAsync("mstest_getOptionInstrument", new object[] {
                    contract}, this.mstest_getOptionInstrumentOperationCompleted, userState);
    }
    
    private void Onmstest_getOptionInstrumentOperationCompleted(object arg) {
        if ((this.mstest_getOptionInstrumentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.mstest_getOptionInstrumentCompleted(this, new mstest_getOptionInstrumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://test.myaspect.net/webservice/aspectws", RequestNamespace="https://my.oilspace.net/webservice/aspectws/schema.xsd", ResponseElementName="MyQueryResponse", ResponseNamespace="https://my.oilspace.net/webservice/aspectws/schema.xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("costs")]
    public MyQueryResponseCosts myQuery() {
        object[] results = this.Invoke("myQuery", new object[0]);
        return ((MyQueryResponseCosts)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginmyQuery(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("myQuery", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public MyQueryResponseCosts EndmyQuery(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MyQueryResponseCosts)(results[0]));
    }
    
    /// <remarks/>
    public void myQueryAsync() {
        this.myQueryAsync(null);
    }
    
    /// <remarks/>
    public void myQueryAsync(object userState) {
        if ((this.myQueryOperationCompleted == null)) {
            this.myQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmyQueryOperationCompleted);
        }
        this.InvokeAsync("myQuery", new object[0], this.myQueryOperationCompleted, userState);
    }
    
    private void OnmyQueryOperationCompleted(object arg) {
        if ((this.myQueryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.myQueryCompleted(this, new myQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://test.myaspect.net/webservice/aspectws", RequestNamespace="https://my.oilspace.net/webservice/aspectws/schema.xsd", ResponseElementName="UpdateDCResponse", ResponseNamespace="https://my.oilspace.net/webservice/aspectws/schema.xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("result")]
    public UpdateDCResponseResult[] updateDC([System.Xml.Serialization.XmlElementAttribute("ETO")] updateDCETO[] ETO) {
        object[] results = this.Invoke("updateDC", new object[] {
                    ETO});
        return ((UpdateDCResponseResult[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginupdateDC(updateDCETO[] ETO, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("updateDC", new object[] {
                    ETO}, callback, asyncState);
    }
    
    /// <remarks/>
    public UpdateDCResponseResult[] EndupdateDC(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((UpdateDCResponseResult[])(results[0]));
    }
    
    /// <remarks/>
    public void updateDCAsync(updateDCETO[] ETO) {
        this.updateDCAsync(ETO, null);
    }
    
    /// <remarks/>
    public void updateDCAsync(updateDCETO[] ETO, object userState) {
        if ((this.updateDCOperationCompleted == null)) {
            this.updateDCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateDCOperationCompleted);
        }
        this.InvokeAsync("updateDC", new object[] {
                    ETO}, this.updateDCOperationCompleted, userState);
    }
    
    private void OnupdateDCOperationCompleted(object arg) {
        if ((this.updateDCCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.updateDCCompleted(this, new updateDCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://my.oilspace.net/webservice/aspectws/schema.xsd")]
public partial class addOptionPriceInstrumentprice {
    
    private string optiontypeField;
    
    private System.DateTime expiredayField;
    
    private double priceField;
    
    private System.DateTime startdayField;
    
    private System.DateTime contractField;
    
    private string pricinggroupField;
    
    private System.DateTime dayField;
    
    private string instrumentField;
    
    private double strikepriceField;
    
    private bool iscallField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("option-type")]
    public string optiontype {
        get {
            return this.optiontypeField;
        }
        set {
            this.optiontypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expire-day", DataType="date")]
    public System.DateTime expireday {
        get {
            return this.expiredayField;
        }
        set {
            this.expiredayField = value;
        }
    }
    
    /// <remarks/>
    public double price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("start-day", DataType="date")]
    public System.DateTime startday {
        get {
            return this.startdayField;
        }
        set {
            this.startdayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime contract {
        get {
            return this.contractField;
        }
        set {
            this.contractField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pricing-group")]
    public string pricinggroup {
        get {
            return this.pricinggroupField;
        }
        set {
            this.pricinggroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
        }
    }
    
    /// <remarks/>
    public string instrument {
        get {
            return this.instrumentField;
        }
        set {
            this.instrumentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("strike-price")]
    public double strikeprice {
        get {
            return this.strikepriceField;
        }
        set {
            this.strikepriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("is-call")]
    public bool iscall {
        get {
            return this.iscallField;
        }
        set {
            this.iscallField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://my.oilspace.net/webservice/aspectws/schema.xsd")]
public partial class addOptionPriceBulkInstrumentprice {
    
    private string optiontypeField;
    
    private System.DateTime expiredayField;
    
    private System.DateTime startdayField;
    
    private System.DateTime contractField;
    
    private string pricinggroupField;
    
    private string instrumentField;
    
    private string pricedataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("option-type")]
    public string optiontype {
        get {
            return this.optiontypeField;
        }
        set {
            this.optiontypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expire-day", DataType="date")]
    public System.DateTime expireday {
        get {
            return this.expiredayField;
        }
        set {
            this.expiredayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("start-day", DataType="date")]
    public System.DateTime startday {
        get {
            return this.startdayField;
        }
        set {
            this.startdayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime contract {
        get {
            return this.contractField;
        }
        set {
            this.contractField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pricing-group")]
    public string pricinggroup {
        get {
            return this.pricinggroupField;
        }
        set {
            this.pricinggroupField = value;
        }
    }
    
    /// <remarks/>
    public string instrument {
        get {
            return this.instrumentField;
        }
        set {
            this.instrumentField = value;
        }
    }
    
    /// <remarks/>
    public string pricedata {
        get {
            return this.pricedataField;
        }
        set {
            this.pricedataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://my.oilspace.net/webservice/aspectws/schema.xsd")]
public partial class GetAllOptionInstrumentsResponseGetAllOptionInstruments {
    
    private GetAllOptionInstrumentsResponseGetAllOptionInstrumentsEtoInstrument[] itemsField;
    
    private GetAllOptionInstrumentsResponseGetAllOptionInstrumentsEoInstrument[] items1Field;
    
    private GetAllOptionInstrumentsResponseGetAllOptionInstrumentsAoInstrument[] items2Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("etoInstrument")]
    public GetAllOptionInstrumentsResponseGetAllOptionInstrumentsEtoInstrument[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("eoInstrument")]
    public GetAllOptionInstrumentsResponseGetAllOptionInstrumentsEoInstrument[] Items1 {
        get {
            return this.items1Field;
        }
        set {
            this.items1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("aoInstrument")]
    public GetAllOptionInstrumentsResponseGetAllOptionInstrumentsAoInstrument[] Items2 {
        get {
            return this.items2Field;
        }
        set {
            this.items2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://my.oilspace.net/webservice/aspectws/schema.xsd")]
public partial class GetAllOptionInstrumentsResponseGetAllOptionInstrumentsEtoInstrument {
    
    private string nameField;
    
    private string codeField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://my.oilspace.net/webservice/aspectws/schema.xsd")]
public partial class GetAllOptionInstrumentsResponseGetAllOptionInstrumentsEoInstrument {
    
    private string nameField;
    
    private string codeField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://my.oilspace.net/webservice/aspectws/schema.xsd")]
public partial class GetAllOptionInstrumentsResponseGetAllOptionInstrumentsAoInstrument {
    
    private string nameField;
    
    private string codeField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://my.oilspace.net/webservice/aspectws/schema.xsd")]
public partial class IsBankHolidayResponseIsBankHoliday {
    
    private bool resultField;
    
    /// <remarks/>
    public bool result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://my.oilspace.net/webservice/aspectws/schema.xsd")]
public partial class Mstest_getOptionInstrumentResponseGetOptionInstrument {
    
    private string instrumentField;
    
    /// <remarks/>
    public string instrument {
        get {
            return this.instrumentField;
        }
        set {
            this.instrumentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://my.oilspace.net/webservice/aspectws/schema.xsd")]
public partial class MyQueryResponseCosts {
    
    private MyQueryResponseCostsCost[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cost")]
    public MyQueryResponseCostsCost[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://my.oilspace.net/webservice/aspectws/schema.xsd")]
public partial class MyQueryResponseCostsCost {
    
    private string labelField;
    
    private double amountField;
    
    /// <remarks/>
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public double amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://my.oilspace.net/webservice/aspectws/schema.xsd")]
public partial class updateDCETO {
    
    private string nameField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://my.oilspace.net/webservice/aspectws/schema.xsd")]
public partial class UpdateDCResponseResult {
    
    private string nameField;
    
    private bool successField;
    
    private string messageField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public bool success {
        get {
            return this.successField;
        }
        set {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void addOptionPriceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void addOptionPriceBulkCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getAllOptionInstrumentsCompletedEventHandler(object sender, getAllOptionInstrumentsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getAllOptionInstrumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getAllOptionInstrumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public GetAllOptionInstrumentsResponseGetAllOptionInstruments Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((GetAllOptionInstrumentsResponseGetAllOptionInstruments)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void isBankHolidayCompletedEventHandler(object sender, isBankHolidayCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class isBankHolidayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal isBankHolidayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public IsBankHolidayResponseIsBankHoliday Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((IsBankHolidayResponseIsBankHoliday)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void mstest_getOptionInstrumentCompletedEventHandler(object sender, mstest_getOptionInstrumentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mstest_getOptionInstrumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal mstest_getOptionInstrumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Mstest_getOptionInstrumentResponseGetOptionInstrument Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Mstest_getOptionInstrumentResponseGetOptionInstrument)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void myQueryCompletedEventHandler(object sender, myQueryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class myQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal myQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public MyQueryResponseCosts Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MyQueryResponseCosts)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void updateDCCompletedEventHandler(object sender, updateDCCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class updateDCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal updateDCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public UpdateDCResponseResult[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((UpdateDCResponseResult[])(this.results[0]));
        }
    }
}
